# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several checks:
# - fmt: checks that the code is formatted according to rustfmt
# - clippy: checks that the code does not contain any clippy warnings
# - doc: checks that the code can be documented without errors
# - hack: check combinations of feature flags
# - msrv: check that the msrv specified in the crate is correct
permissions:
  contents: read
# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [main]
  pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check
jobs:

  fmt:
    runs-on: ubuntu-latest
    name: nightly / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        # Get early warning of new lints which are regularly introduced in beta channels.
        toolchain: [stable, beta]
        chip-rev: [r1, r3, r4, r5]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy ${{ matrix.chip-rev }}
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          clippy_flags: --features ${{ matrix.chip-rev }} -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Enable once we have a released crate
  # UPDATE: Crate is released but because of mutually exclusive features, this will never succeed :c
  # semver:
  #   runs-on: ubuntu-latest
  #   name: semver
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: Install stable
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: rustfmt
  #     - name: cargo-semver-checks
  #       uses: obi1kenobi/cargo-semver-checks-action@v2

  doc:
    # run docs generation on nightly rather than stable. This enables features like
    # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html which allows an
    # API be documented as only available in some specific platforms.
    # UPDATE: nightly seems broken right now, reverting to stable
    runs-on: ubuntu-latest
    name: stable / doc
    strategy:
      matrix:
        chip-rev: [r1, r3, r4, r5]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo doc ${{ matrix.chip-rev }}
        run: cargo doc --no-deps --features ${{ matrix.chip-rev }}
        env:
          RUSTDOCFLAGS: --cfg docsrs

  deny:
    # cargo-deny checks licenses, advisories, sources, and bans for
    # our dependencies.
    runs-on: ubuntu-latest
    name: ubuntu / stable / deny
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          manifest-path: ./Cargo.toml
          command: check
          arguments: --all-features

  msrv:
    # check that we can build using the minimal rust version that is specified by this crate
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        chip-rev: [r1, r3, r4, r5]
        msrv: ["1.85"] # We're relying on namespaced-features, which
                       # was released in 1.60
                       #
                       # We also depend on `fixed' which requires rust
                       # 1.71
                       #
                       # Additionally, we depend on embedded-hal-async
                       # which requires 1.75
                       #
                       # embassy-time requires 1.79 due to
                       # collapse_debuginfo
                       #
                       # bitfield-struct requires 1.83
                       #
                       # device-driver requires 1.85 for Rust 2024 edition
        toolchain: [stable]
    name: ubuntu / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo +${{ matrix.toolchain }} check ${{ matrix.chip-rev }}
        run: cargo check --features ${{ matrix.chip-rev }}
